### ISSUE TITLE
goodies? donuts? treats?

### ISSUE THREAD

**Issue by pdurbin** [good-labs/logo#2]
The "gl" logo is a fine start but should we consider making a new logo based on goodies? As I expressed at https://gitter.im/good-labs/community?at=5cc8de1c8790b0307e2d7c96 to me goodies are donuts or other treats. Please feel free to close if we're happy with the current logo:

![good-labs](https://user-images.githubusercontent.com/21006/57003929-32068580-6b98-11e9-8582-5cb6e4599438.png)

**Comment by vsoch** [comment]
Simple, letter based logos are known for working well, however I see no reason we can’t create a set of Good Labs “goodies” icons if someone has the creative bandwidth.

**Comment by pdurbin** [comment]
@vsoch when you're ready, just say the word and I can post a job to https://opensourcedesign.net/jobs/

**Comment by vsoch** [comment]
Give me a few more days to put together some faq and example scenarios. Who would pay for such logos?

**Comment by pdurbin** [comment]
One can flag a job as "gratis" on the Open Source Design job board. 😄 

I guess this ties into my FUNDING.md idea where we'd simply put "None." 😄

**Comment by vsoch** [comment]
Speaking of that idea - how about writing it up as a project proposal? It's really great :)

**Comment by pdurbin** [comment]
@vsoch if you're talking about writing up FUNDING.md you've already done so at https://github.com/good-labs/good-labs.github.io/issues/15 which is perfect.

For the logo, somehow I was thinking of a donut and a beaker today. Well, a flask actually.

**Comment by pdurbin** [comment]
Maybe these:

- donut: https://thenounproject.com/search/?q=donut&i=1321719
- flask: https://thenounproject.com/search/?q=flask&i=1295549

<img width="307" alt="Screen Shot 2019-05-01 at 6 36 47 PM" src="https://user-images.githubusercontent.com/21006/57047638-18207d80-6c40-11e9-8739-e51674c41d49.png">
<img width="245" alt="Screen Shot 2019-05-01 at 6 36 38 PM" src="https://user-images.githubusercontent.com/21006/57047639-18b91400-6c40-11e9-96ea-159a2f58bd37.png">

I don't know. Or we can just keep the current logo. 😄

**Comment by vsoch** [comment]
Letters are much better than random free graphics found on the internet. Let's leave this issue scoped to designs for goodies (and not changing the logo). If the logo is to be done professionally, it would be a different thing (likely commissioned with 99 designs or similar). But not random internet art :P

**Comment by pdurbin** [comment]
Well, they aren't completely random. I looked at a couple dozen donuts and flasks. 😄 

I'm not sure that this issue provides much value being open so I'll just close it. I'm fine with whatever.
